### ISSUE TITLE
Openonderwijsdata.nl Ssl certificate expired

### ISSUE THREAD

**Issue by robfuncken** [openstate/openonderwijsdata-api#37]
The SSL certificate for openonderwijsdata.nl is expired and the host is not reachable anymore. 

I don't know if the website is maintained by this repo maintainer but wanted to make an issue regarding this.

**Comment by siccovansas** [comment]
Thanks @robfuncken! Our own monitoring also detected this problem and it is now fixed.

Out of curiosity: openonderwijsdata.nl is not actively used anymore and mainly kept around as an archive. Was it just a coincidence that you visited the website during the two days that the certificate was expired, or are you monitoring/using the website structurally?
